# Generated by Django 5.2.7 on 2025-10-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clientprofile_age_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='email',
            field=models.CharField(blank=True),
        ),
    ]
