# Generated by Django 5.2.7 on 2025-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='updated_at',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
