# Generated by Django 5.2.7 on 2025-10-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_clientprofile_age_alter_clientprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='email',
        ),
    ]
