# Generated by Django 5.2.7 on 2025-10-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_number_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mastercard', 'MasterCard'), ('visa', 'Visa'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('simulated', 'Simulated Payment')], max_length=20, null=True),
        ),
    ]
